# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='group',
            new_name='study_group',
        ),
    ]
