# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160508_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='study_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Group', verbose_name='Учебная группа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='users.Subject', verbose_name='Предметы'),
        ),
    ]
