# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160512_2039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AlterField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='constructor.Category', verbose_name='Предметы'),
        ),
    ]
