# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160514_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='secret_key',
            field=models.CharField(default='code', max_length=25),
        ),
    ]
