# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20160406_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='code',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
