# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20160508_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
