# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20160508_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tested',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Specialization'),
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
