# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-08 03:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20160508_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analytic',
            options={'verbose_name': 'Ответ опрашиваемого', 'verbose_name_plural': 'Ответы опрашиваемых'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='tested',
            options={'verbose_name': 'Опрашиваемого', 'verbose_name_plural': 'Опрашиваемые'},
        ),
        migrations.AlterField(
            model_name='analytic',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.Answer', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='tested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Tested', verbose_name='Опрашиваемый'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tested',
            name='course',
            field=models.IntegerField(blank=True, null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='tested',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата опроса'),
        ),
        migrations.AlterField(
            model_name='tested',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='tested',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Specialization', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='tested',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.Test', verbose_name='Анкета'),
        ),
    ]
