# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_answer_analytics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='time',
        ),
        migrations.RemoveField(
            model_name='test',
            name='public_access',
        ),
        migrations.AlterField(
            model_name='test',
            name='time_completion',
            field=models.IntegerField(default=20),
        ),
    ]
