# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0006_test_group_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('public_access', models.BooleanField(default=False)),
                ('questions', models.ManyToManyField(to='constructor.Query')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.Test')),
            ],
        ),
    ]
