# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0007_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='questions',
            field=models.ManyToManyField(blank=True, to='constructor.Query'),
        ),
    ]
