# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0008_auto_20160519_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='time',
            field=models.IntegerField(default=True),
        ),
    ]
