# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0009_option_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
