# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 17:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_answer_analytics'),
        ('tests', '0004_auto_20160405_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbationerAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.Answer', verbose_name='Ответ')),
            ],
            options={
                'verbose_name_plural': 'Ответы Тестируемых',
                'verbose_name': 'Ответ Тестируемого',
            },
        ),
        migrations.AlterModelOptions(
            name='probationer',
            options={'verbose_name': 'Тестируемого', 'verbose_name_plural': 'Тестируемые'},
        ),
        migrations.RemoveField(
            model_name='probationer',
            name='name',
        ),
        migrations.AlterField(
            model_name='probationer',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='probationer',
            name='mark',
            field=models.IntegerField(verbose_name='Отметка'),
        ),
        migrations.AlterField(
            model_name='probationer',
            name='precent',
            field=models.FloatField(verbose_name='Процент'),
        ),
        migrations.AlterField(
            model_name='probationer',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.Test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='probationer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Тестируемый'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='probationeranswers',
            name='probationer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Probationer', verbose_name='Тестируемый'),
        ),
    ]
