# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_probationer_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probationer',
            name='test',
        ),
    ]
