# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_remove_probationer_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProbationerAnswers',
            new_name='ProbationerAnswer',
        ),
    ]
